[package]
name = "wsrpc"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
warp = { git = "https://github.com/seanmonstar/warp.git", rev = "fbbbc5b8377914463e4411ef6fc48bfd97d15a6d"}
futures = "~0.3"
serde = { version = "~1.0", features = ["derive"] }
serde_json = { version = "~1.0", features = ["raw_value"] }
bytes = "~0.4"
tokio = { package = "tokio", version = "~0.2", features = ["full"] }
tracing = "~0.1"
tracing-futures = "~0.1"

[dev-dependencies]
websocket = "~0.23"
