[package]
name = "wsrpc"
version = "0.1.0"
authors = ["Varga Endre <drewhk@drewhk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.1"
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
bytes = "0.4"
log = "0.4"
tokio = "0.1"

[dev-dependencies]
websocket = "0.22"
